FROM mcr.microsoft.com/azure-functions/base:2.0 as runtime-image

FROM python:3.6-alpine
COPY --from=runtime-image ["/azure-functions-host", "/azure-functions-host"]

# Install aspdotnet core 2.1 alpine runtime on this
RUN apk add --no-cache \
        ca-certificates \
        \
        # .NET Core dependencies
        krb5-libs \
        libgcc \
        libintl \
        libssl1.0 \
        libstdc++ \
        tzdata \
        userspace-rcu \
        zlib \
    && apk -X https://dl-cdn.alpinelinux.org/alpine/edge/main add --no-cache \
        lttng-ust

ARG REPO=microsoft/dotnet
# Configure web servers to bind to port 80 when present
ENV ASPNETCORE_URLS=http://+:80 \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true \
    # Set the invariant mode since icu_libs isn't included (see https://github.com/dotnet/announcements/issues/20)
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true

# Install ASP.NET Core
ENV ASPNETCORE_VERSION 2.1.7

RUN apk add --no-cache --virtual .build-deps \
        openssl \
    && wget -O aspnetcore.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/$ASPNETCORE_VERSION/aspnetcore-runtime-$ASPNETCORE_VERSION-linux-musl-x64.tar.gz \
    && aspnetcore_sha512='08320fd139768557fe962c06c0316df8d30312d35a354f5d4dd6dc98c5093bda7b0facd694bd7406f3c6543d383296f7cba7d759367ee4cfdbc8ac98062cd289' \
    && echo "$aspnetcore_sha512  aspnetcore.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf aspnetcore.tar.gz -C /usr/share/dotnet \
    && rm aspnetcore.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet \
    && apk del .build-deps

# Install Python libs
RUN apk update && apk add --no-cache python3-dev gcc bash libc6-compat

# Install Python worker
RUN apk add --no-cache --virtual build-dependencies \
        build-base
ENV WORKER_TAG=1.0.0a6 \
    AZURE_FUNCTIONS_PACKAGE_VERSION=1.0.0a5 \
    LANG=C.UTF-8 \
    PYTHON_VERSION=3.6.6 \
    PYTHON_PIP_VERSION=18.0 \
    ACCEPT_EULA=Y \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN wget https://github.com/Azure/azure-functions-python-worker/archive/$WORKER_TAG.tar.gz && \
    tar xvzf $WORKER_TAG.tar.gz && \
    mv azure-functions-python-worker-* azure-functions-python-worker && \
    cp -R /azure-functions-python-worker/python /azure-functions-host/workers/python && \
    pip3 install azure-functions==$AZURE_FUNCTIONS_PACKAGE_VERSION azure-functions-worker==$WORKER_TAG
ENV AzureWebJobsScriptRoot=/home/site/wwwroot

# Start functions host
CMD [ "dotnet", "/azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost.dll" ]

# Start python worker
COPY ./python-context/start.sh /azure-functions-host/workers/python/
RUN chmod +x /azure-functions-host/workers/python/start.sh
COPY ./python-context/worker.config.json /azure-functions-host/workers/python/
ENV workers:python:path /azure-functions-host/workers/python/start.sh
